export { default as Header } from './Header/Header'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Skills } from './Skills/Skills'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'